### ISSUE TITLE
support daemon 

### ISSUE THREAD

**Issue by pierce300** [repeatedly/fluent-plugin-stdin#1]
Hi 
  i need to run daemon for stdtin plugin , how do it?

Thanks

**Comment by repeatedly** [comment]
Sorry, I don't understand what you said.
What does 'daemon' mean?
Your program is daemonzied application?

**Comment by pierce300** [comment]
yes,my application is daemonzied,i need from read stdout  to stdin

**Comment by repeatedly** [comment]
AFAIK, there is no way because daemonized program closes stdin/stdout.
If your application could be launched by another script, you can use in_exec: http://docs.fluentd.org/articles/in_exec

**Comment by pierce300** [comment]
My daemonized program stdout is open,it's log to stdout,so i need read data to stdin of flunet

**Comment by repeatedly** [comment]
If so, `your program | fluentd` doesn't work?

**Comment by pierce300** [comment]
yes  fluent-plugin-stdin doesn't work,
it repeat to generate below log
[error]: fluentd main process died unexpectedly. restarting.

**Comment by repeatedly** [comment]
Hmm... that's weird.
I don't have your program so if the problem is stdin plugin,
you need to debug the input plugin on your environment or report the minimal test case.

**Comment by wujiandong** [comment]
Hi
  I use  --no-supversize and  to  resolve problem, I don't understand this parameter is what role
